### ISSUE TITLE
docs: fix logo in readme

### ISSUE THREAD

**Issue by xkrishguptaa** [xkrishguptaa/bot-dc-htm#19]
![image](https://github.com/xkrishguptaa/bot-dc-htm/assets/135469703/9dc20d6d-53f8-41c3-b356-9763db5e57d4)

fix the logo in the readme by adding the width and height:

![image](https://github.com/xkrishguptaa/bot-dc-htm/assets/135469703/326e6319-33ca-4b67-866f-d44e6751ef03)

**Comment by adi-ray** [comment]
I would love to work on this issue. Can you please assign me ?

**Comment by xkrishguptaa** [comment]
Go ahead 🚀

**Comment by sonukmrsah** [comment]
![Screenshot_2023-10-03-21-38-43-35_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/xkrishguptaa/bot-dc-htm/assets/78902659/e288ca4e-9fd3-463b-919a-8e909da897af)
Just to confirm that are saying that logo is not responsive when the screen size changes to smartphone?

**Comment by xkrishguptaa** [comment]
No it is not responsive either way, I want the max height to be 150px, you have to go into the picture's properties and find its current sizes then just divide then resize the file to 150px in height. However this issue is already assigned to someone, please look at some other issue :)

**Comment by adi-ray** [comment]
I have made the required changes making it responsive. 

![image](https://github.com/xkrishguptaa/bot-dc-htm/assets/96347576/07ade10e-547a-4936-b5fe-3961abff55d7)

Please @xkrishguptaa review so that I can make a PR .

**Comment by xkrishguptaa** [comment]
fixed in some PR ig 😅
