### ISSUE TITLE
ci: add semantic-release

### ISSUE THREAD

**Issue by xkrishguptaa** [xkrishguptaa/bot-dc-htm#20]
Add [semantic-release/semantic-release](https://github.com/semantic-release/semantic-release) to the project

**Comment by trishanu-init** [comment]
@xkrishguptaa can you assign this issue to me

**Comment by kaushalkumar99** [comment]
Working on this issue... @xkrishguptaa can u please assign it to me

**Comment by xkrishguptaa** [comment]
@trishanu-init asked first, I'll assign them, you can look at our other issues @kaushalkumar99

**Comment by kaushalkumar99** [comment]
ok no issues ( :

**Comment by trishanu-init** [comment]
I'm working on it !

**Comment by trishanu-init** [comment]
@xkrishguptaa I need npm credentials please contact me on discord.
