### ISSUE TITLE
feat: add issue templates

### ISSUE THREAD

**Issue by xkrishguptaa** [xkrishguptaa/bot-dc-htm#21]
Add issue templates to the repo

- Documentation
- Command Request
- Feature Request
- Bug Report

**Comment by imkrishnasarathi** [comment]
How should this be done. Can you explain a bit elaborately? I could work on this

**Comment by caycun** [comment]
@xkrishguptaa can I work on this?

**Comment by imkrishnasarathi** [comment]
I'll work on this. Reserve this for me. I'll submit a PR by tomorrow noon. Don't break trust. इंतज़ार करना

**Comment by imkrishnasarathi** [comment]
Can you assign this to me?

**Comment by xkrishguptaa** [comment]
@caycun @imkrishnasarathi did I ask before you, so I will assign them, you can spilt the issue templates if want but it is a decision amongst you :)

**Comment by imkrishnasarathi** [comment]
yo @caycun what do you think? Let us work on different issue templates.

**Comment by imkrishnasarathi** [comment]
Shit I shouldn't have done that. This issue should not close. I only did the Bug Report Template

**Comment by caycun** [comment]
sure @imkrishnasarathi  Ill work on feature request template

**Comment by imkrishnasarathi** [comment]
@caycun Great!

**Comment by xkrishguptaa** [comment]
Merged in #34
