### ISSUE TITLE
docs: make a pr template

### ISSUE THREAD

**Issue by xkrishguptaa** [xkrishguptaa/bot-dc-htm#24]
You can copy the one in EddieHubCommunity/Biodrop

The file is .github/PULL_REQUEST_TEMPLATE.md

The file name here will also be the same ✌️

**Comment by xkrishguptaa** [comment]
@sonukmrsah have you started working on this? If yes, I'll assign you and close @bibaswan7's pr

Otherwise, I'll merge it and you can please pick some other issue

(You are doing absolutely perfect here, @bibaswan7 shouldn't have created the PR without getting assignment, but I don't want to upset them by closing it if no progress has been made here)

**Comment by bibaswan7** [comment]
I am so sorry for being so disrespectful. Sorry guys @sonukmrsah @xkrishguptaa

**Comment by sonukmrsah** [comment]
No problem @bibaswan7 I am also learning to contribute so no worries. In fact, you have done great work. @xkrishguptaa please consider the PR to be merged if it looks good to you!

**Comment by xkrishguptaa** [comment]
Thank you for being so kind @sonukmrsah <3 appreciate it!

**Comment by bibaswan7** [comment]
Right, thats really kind of you @sonukmrsah .God bless :)
