### ISSUE TITLE
feat: add linting with eslint

### ISSUE THREAD

**Issue by xkrishguptaa** [xkrishguptaa/bot-dc-htm#25]
Setup eslint in the project

**Comment by imkrishnasarathi** [comment]
You want `npm run lint` to check for linting errors and `npm run lint:fix` to automatically fix some of them - right?

**Comment by inkollusireeshaadharani** [comment]
hi @xkrishguptaa . Can I work on this issue?

**Comment by xkrishguptaa** [comment]
Yes @imkrishnasarathi but with yarn

**Comment by xkrishguptaa** [comment]
Go ahead @inkollusireeshaadharani
